# Generated by Django 2.2 on 2019-04-23 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mana', '0002_delete_customers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=200)),
                ('customer_lastname', models.CharField(max_length=200)),
                ('customer_type', models.CharField(max_length=200)),
            ],
        ),
    ]
