# Generated by Django 2.2 on 2019-04-23 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mana', '0003_customers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customers',
        ),
    ]
