# Generated by Django 2.2 on 2019-04-23 02:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mana', '0004_delete_customers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=200)),
                ('customer_lastname', models.CharField(max_length=200)),
                ('service_type', models.CharField(max_length=200)),
                ('service_date', models.DateTimeField(verbose_name=datetime.datetime(2019, 4, 23, 2, 20, 23, 875000, tzinfo=utc))),
                ('customer_id', models.IntegerField()),
                ('phone_number', models.IntegerField()),
            ],
        ),
    ]
