# Generated by Django 2.1.3 on 2019-04-23 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mana', '0005_customers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='service_date',
            field=models.DateTimeField(),
        ),
    ]
