# Generated by Django 2.1.3 on 2019-04-26 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mana', '0006_auto_20190423_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='customer_id',
            field=models.IntegerField(verbose_name=((1, 'yes'), (2, 'no'))),
        ),
    ]
