# Generated by Django 2.1.3 on 2019-04-26 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mana', '0007_auto_20190426_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='customer_id',
            field=models.IntegerField(choices=[(1, 'yes'), (2, 'no')]),
        ),
    ]
