# Generated by Django 2.2 on 2019-04-28 04:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mana', '0008_auto_20190426_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='description',
            field=models.CharField(default=3, max_length=400),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customers',
            name='customer_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='customers',
            name='service_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 28, 4, 13, 32, 436523, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='customers',
            name='service_type',
            field=models.IntegerField(choices=[(1, 'repair'), (2, 'sell')], default=1),
        ),
    ]
