# Generated by Django 2.2 on 2019-04-28 04:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mana', '0009_auto_20190428_0844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='service_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 28, 4, 14, 23, 15625, tzinfo=utc)),
        ),
    ]
