# Generated by Django 2.1.3 on 2019-05-04 18:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mana', '0010_auto_20190428_0844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='service_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 4, 18, 27, 43, 155214, tzinfo=utc)),
        ),
    ]
