# Generated by Django 2.2 on 2019-05-05 08:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mana', '0011_auto_20190504_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='service_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 5, 8, 34, 38, 322265, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='customers',
            name='service_type',
            field=models.IntegerField(choices=[(1, 'درحال تعمیر'), (2, 'تعمیر شده'), (3, 'عدم امکان تعمیر')], default=1),
        ),
    ]
